# to run 
# podman-compose up

services:
  db:
    container_name: db
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volume:
      - rpi: /var/lib/pgsql/data
    network: 
      - pgnetwork

db_admin:
  image: docker.io/dpage/pgadmin4
  container_name: db_admin
  environment:
    PGAMDIN_DEFAULT_PASSWORD: 1234
    PGADMIN_DEFAULT_EMAIL: caio@email.com
  ports:
      - "9091:80"
  network: 
    - pgnetwork
  depends_on: 
    - db

volume: {}
network:
  pgnetwork: {}